export const FEED_IMPRESSION_VIEW_AREA_PERCENT = 80;
export const FEED_IMPRESSION_MINIMUM_VIEW_TIME_MS = 2000;
export const FEED_IMPRESSION_FLUSH_DELAY_MS = 3000;
export const FEED_IMPRESSION_BATCH_SIZE = 10;
